a_classroom/urls.py
from django.urls import path
from . import views

app_name = "a_classroom"
urlpatterns = [
    path("", views.index, name="index"),
    #
    path("subject/<str:subject_id>/", views.view_subject, name="v"),
    #
    path("create/subject/", views.CreateSubjectView.as_view(), name="create-subject"),
    #
    path("about/", views.about, name="about"),
    path("approve/<int:user_id>/", views.ApproveUserAdminView.as_view(), name="approve"),
    path("activity/<str:activity_id>/", views.ActivityView.as_view(), name="view-activity"),
    path("settings/", views.user_settings, name="setting"),
    path("edit/", views.EditAccountView.as_view(), name="edit-account"),
    path("users/", views.AdminDashboardView.as_view(), name="get-users"),
    path("pending/", views.PendingUsersView.as_view(), name="pending-users"),
    path("subjects/", views.SubjectListView.as_view(), name="get-subjects"),
    path("archived/", views.ArchivedSubjectListView.as_view(), name="archived-subjects"),
]

b_enrollment/urls.py
from django.urls import path
from . import views

app_name = "b_enrollment"
urlpatterns = [
	path("", views.JoinClassView.as_view(), name="join-a-class"),
	path("p/", views.UploadProfileView.as_view(), name="upload-profile"),]

d_compiler/urls.py
from django.urls import path
from . import views

app_name = "d_compiler"
urlpatterns = [
    path("", views.RunCodeView.as_view(), name="index"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('c/', include("a_classroom.urls")),
    path('e/', include("b_enrollment.urls")),
    path('a/', include("c_activities.urls")),
    path('p/', include("d_compiler.urls")),
    path('', include("register.urls")),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from . import views

app_name = "register"
urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
]

a_classroom/models.py
from django.db import models
from django.contrib.auth.models import User
import random
import string

class Section(models.Model):
    name = models.CharField(max_length=100, unique=True)
    students = models.ManyToManyField(User, related_name="sections", blank=True)

class Subject(models.Model):
    instructor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subjects')
    subject_id = models.CharField(max_length=8, unique=True, editable=False)
    name = models.CharField(max_length=200)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, related_name='subjects')
    course_code = models.TextField(blank=True)
    students = models.ManyToManyField(User, related_name='joined_subjects', blank=True, through='b_enrollment.StudentSubject')
    is_archived = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.subject_id:
            self.subject_id = self.generate_unique_subject_id()
        super().save(*args, **kwargs)

    @staticmethod
    def generate_unique_subject_id():
        characters = string.ascii_uppercase + string.digits
        while True:
            unique_id = ''.join(random.choices(characters, k=8))
            if not Subject.objects.filter(subject_id=unique_id).exists():
                return unique_id

a_classroom/forms.py
from django import forms

class CreateSubjectForm(forms.Form):
    course_code = forms.CharField(label = "Course Code", max_length = 100)
    section_name = forms.CharField(label = "Section", max_length = 100)
    name = forms.CharField(label = "Subject", max_length = 200)

register/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
import uuid

class RegisterForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={
            "autocomplete": "email",
            "placeholder": "Email Address..."
        })
    )

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "password1", "password2"]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].widget.attrs.update({
            "placeholder": "Password"
        })
        self.fields["password2"].widget.attrs.update({
            "placeholder": "Confirm Password"
        })
        self.fields["first_name"].widget.attrs.update({"placeholder" : "First Name"})
        self.fields["last_name"].widget.attrs.update({"placeholder" : "Last Name"})

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email is already in use.")

        return email
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data['email'].split('@')[0] + uuid.uuid4().hex[:6]
        if commit:
            user.save()
        return user

class CustomLoginForm(forms.Form):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={
            "autocomplete": "email",
            "placeholder": "Email Address..."
        })
    )
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}))

a_classroom/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Section, Subject
from c_activities.models import Activity, ActivitySubmission
from b_enrollment.models import UserProfile, StudentSubject
from django.urls import reverse
import json
from django.http import JsonResponse, HttpResponseRedirect, HttpRequest
from .forms import CreateSubjectForm
from django.contrib import messages
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.core.mail import send_mail
# Create your views here.
def index(request):
    if not hasattr(request.user, 'userprofile'):
        messages.error(request, "Your account is incomplete. Please contact the administrator.")
        return redirect('register:login')

    if request.user.userprofile.role == "Admin":
        if request.headers.get("HX-Request") == "true":
            return render(request, 'a_classroom/sidebar/sidebar.html')
        return render(request, 'a_classroom/a.admin/admin.html')

    elif request.user.userprofile.role == "Instructor":
        subjects = Subject.objects.filter(instructor=request.user).order_by('-subject_id')
        if request.headers.get("HX-Request") == "true":
            return render(request, 'a_classroom/sidebar/sidebar.html', {"subjects": subjects})

        return render(request, 'a_classroom/b.instructor/instructor.html', {"subjects" : subjects})

    elif request.user.userprofile.role == "Student":
        subjects = list(request.user.joined_subjects.all())
        if request.headers.get("HX-Request") == "true":
            return render(request, 'a_classroom/sidebar/sidebar.html', {"subjects" : subjects})

        return render(request, 'a_classroom/c.student/student.html', {"subjects" : subjects})

    return render(request, 'a_classroom/index.html')

@method_decorator(never_cache, name='dispatch')
class CreateSubjectView(View):
    def get(self, request):
        form = CreateSubjectForm()
        sections = Section.objects.all()
        return render(request, 'a_classroom/create_subject.html', {"form": form, "sections" : sections})
    
    def post(self, request):
        form = CreateSubjectForm(request.POST)
        if form.is_valid():
            course_code = form.cleaned_data["course_code"]
            section_name = form.cleaned_data["section_name"]
            name = form.cleaned_data["name"]

            section, created = Section.objects.get_or_create(name=section_name)

            subject = Subject.objects.filter(
                instructor=request.user, 
                course_code=course_code,
                section=section, 
                name=name).first()

            if subject:
                messages.error(request, f"{course_code} for section {section_name} already exists.")
            else:
                subject = Subject.objects.create(
                    instructor=request.user,
                    course_code=course_code,
                    section=section,
                    name=name
                )
                messages.success(request, f"{course_code} for section {section_name} has been created.")
            
            form = CreateSubjectForm() 
            
            return HttpResponseRedirect(reverse("a_classroom:v", args=[subject.subject_id]))

        return render(request, 'a_classroom/create_subject.html', {"form": form})

def user_settings(request):
    user_profile = UserProfile.objects.select_related('user').get(user = request.user)
    email = request.user.email
    return render(request, 'a_classroom/setting.html', {"user_profile" : user_profile, "email" : email})

def about(request):
    return render(request, 'a_classroom/about.html')

@never_cache
def view_subject(request, subject_id):
    subject = get_object_or_404(Subject, subject_id = subject_id)
    activities = subject.activities.all().order_by('-created_at')
    students = subject.students.all()
    instructor = subject.instructor.get_full_name()
    trigger = request.headers.get("HX-Trigger")
    if request.headers.get("HX-Request") == "true":
        if trigger == "subject":
            return render(request, 'a_classroom/subject.partials/subject.html', {
                "subject" : subject,
                "activities" : activities
            })
        elif trigger == "classwork":
            return render(request, 'a_classroom/subject.partials/classworks.html', {
                "activities" : activities
            })
        elif trigger == "students":
            return render(request, 'a_classroom/subject.partials/people.html', {
                "subject" : subject,
                "instructor" : instructor,
                "students" : students
            })
    return render(request, 'a_classroom/subject_view.html', {"subject" : subject})

class EditAccountView(View):
    def get(self, request):
        trigger = request.headers.get("HX-Trigger")
        if request.headers.get("HX-Request") == "true":
            if trigger == "edit-account":
                user = get_object_or_404(User, id = request.user.id)
                return render(request, 'a_classroom/profile/edit.account.html', {"user" : user})

    def post(self, request):
        user = get_object_or_404(User, id = request.user.id)

        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        if password:
            user.set_password(password)
            update_session_auth_hash(request, user)

        user.username = username
        user.first_name = first_name
        user.last_name = last_name
        user.save()

        messages.success(request, 'You profile has been updated successfully!')

        return redirect('a_classroom:setting')

class ActivityView(View):
    def get(self, request, activity_id):
        subject_id = request.GET.get('subject_id')
        user_profile = UserProfile.objects.select_related('user').get(user = request.user)
        subject = get_object_or_404(Subject, subject_id = subject_id)
        activity = get_object_or_404(Activity, subject = subject, activity_id = activity_id)
        if request.user.userprofile.role == "Instructor":
            submissions = ActivitySubmission.objects.filter(activity = activity).select_related('student')
            return render(request, 'c_activities/activity.partial/student.submission.html', {"submissions" : submissions, "user_profile" : user_profile, "subject_id" : subject_id})
        elif request.user.userprofile.role == "Student":
            submission = ActivitySubmission.objects.filter(activity = activity, student = request.user).first()
            submissions = [submission] if submission else []
            return render(request, 'c_activities/activity.partial/student.compiler.html', {"activity" : activity, "submissions" : submissions, "user_profile" : user_profile, "subject_id" : subject_id, "subject" : subject})
        return HttpResponse("Unhandled request case.", status=400)

class HtmxTemplateView(View):
    queryset = None
    template = None
    htmx_template = None
    htmx_trigger = None
    context_name = None

    def get(self, request: HttpRequest):
        data = self.queryset() if callable(self.queryset) else self.queryset
        trigger = request.headers.get("HX-Trigger")

        if request.headers.get("HX-Request") == "true" and trigger == self.htmx_trigger:
            return render(request, self.htmx_template, {self.context_name: data})

        return render(request, self.template, {self.context_name: data})

class AdminDashboardView(HtmxTemplateView):
    queryset = User.objects.all
    template = 'a_classroom/a.admin/admin.html'
    htmx_template = 'a_classroom/a.admin/users/users.html'
    htmx_trigger = 'all-user'
    context_name = 'all_users'

class PendingUsersView(HtmxTemplateView):
    queryset = lambda self: User.objects.filter(is_active=False)
    template = 'a_classroom/a.admin/users/pending.html'
    htmx_template = 'a_classroom/a.admin/users/pending/pending.users.html'
    htmx_trigger = 'pending'
    context_name = 'pending_users'

class SubjectListView(HtmxTemplateView):
    queryset = Subject.objects.all
    template = 'a_classroom/a.admin/users/subject.html'
    htmx_template = 'a_classroom/a.admin/users/subject/subjects.html'
    htmx_trigger = 'all-subject'
    context_name = 'subjects'

class ArchivedSubjectListView(HtmxTemplateView):
    queryset = lambda self: Subject.objects.filter(is_archived=True)
    template = 'a_classroom/a.admin/users/archived.html'
    htmx_template = 'a_classroom/a.admin/users/subject/archived.subjects.html'
    htmx_trigger = 'archived'
    context_name = 'archived_subjects'

class ApproveUserAdminView(View):
    def post(self, request, user_id):
        user = get_object_or_404(User, id=user_id)
        trigger = request.headers.get("HX-Trigger")

        if request.headers.get("HX-Request") == "true" and trigger == "approve-button":
            user.is_active = True
            user.save()

            # Send approval email
            subject = "Your Account Has Been Approved"
            message = f"""Hello {user.first_name},

            Your account has been approved by the admin.

            If you signed up with Google, your default password is 123. Please change your password after logging in.
            If you registered normally, your account is now active and ready to use.

            Best regards,  
            Admin Team
            """
            try:
                send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [user.email])
            except Exception as e:

a_classroom/templates/a_classroom/about.html
{% extends 'a_classroom/base.html' %}
{% block title %} about html {% endblock %}
{% block content %}
    <div class="flex h-full w-full items-center justify-center">
        <div class="flex border border-solid border-gray-300 h-[500px] w-[700px] overflow-hidden items-center justify-center">
            About Content
        </div>
    </div>
{% endblock %}

a_classroom/templates/a_classroom/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} base html {% endblock %}</title>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    {% tailwind_css %}
</head>
<body>
    {% if messages %}
    <div id="message-container" class="fixed z-50 space-y-2 transform -translate-x-1/2 top-4 left-1/2">
        {% for message in messages %}
        <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative shadow-md w-[300px] text-center" role="alert">
            <span class="block sm:inline">{{ message }}</span>
            <button onclick="this.parentElement.remove()" class="absolute top-0 bottom-0 right-0 px-4 py-3">
                <svg class="w-6 h-6 text-blue-500 fill-current" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                    <title>Close</title>
                    <path d="M14.348 5.652a1 1 0 10-1.414-1.414L10 7.172 7.066 4.238a1 1 0 00-1.414 1.414L8.586 10l-2.934 2.934a1 1 0 001.414 1.414L10 12.828l2.934 2.934a1 1 0 001.414-1.414L11.414 10l2.934-2.934z"/>
                </svg>
            </button>
        </div>
        {% endfor %}
    </div>
    {% endif %}   
    <!-- Below this comment -->
    <div class="
    grid grid-rows-[auto_1fr] min-h-screen max-h-screen font-normal
    {% if request.user.is_authenticated %}
        grid-cols-[200px_1fr]
    {% else %}
        grid-cols-1
    {% endif %}">
        <nav class="flex flex-row items-center justify-between h-[75px] col-span-2 p-6 space-x-6 text-white bg-gray-800 shadow-xl ">
            <ul class="flex flex-row items-center space-x-12">
                <li><a href="{% url 'a_classroom:index' %}"><img class="h-10" src="/media/mysite_images/logo.png" alt="logo.png"></a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'a_classroom:index' %}"
                        class="p-4 transition duration-300 ease-in-out delay-150 transform rounded-lg hover:-translate-y-1 hover:scale-100 hover:bg-gray-500 hover:shadow-lg hover:text-white">Home</a></li>
                        {% if request.user.userprofile.role == "Student" %}
                            <li><a href="{% url 'd_compiler:index' %}"
                                class="p-4 transition duration-300 ease-in-out delay-150 transform rounded-lg hover:-translate-y-1 hover:scale-100 hover:bg-gray-500 hover:shadow-lg hover:text-white">Playground</a></li>
                        {% endif %}
                    <li><a href="{% url 'a_classroom:about' %}?from={{ request.path }}"
                        class="p-4 transition duration-300 ease-in-out delay-150 transform rounded-lg hover:-translate-y-1 hover:scale-100 hover:bg-gray-500 hover:shadow-lg hover:text-white">About</a></li>
                {% else %}
                    <li><a href="{% url 'd_compiler:index' %}"
                        class="p-4 transition duration-300 ease-in-out delay-150 transform rounded-lg hover:-translate-y-1 hover:scale-100 hover:bg-gray-500 hover:shadow-lg hover:text-white">Playground</a></li>
                {% endif %}
            </ul>
            <ul class="flex space-x-12">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'a_classroom:setting' %}?from={{ request.path }}"
                        class="p-4 transition duration-300 ease-in-out delay-150 transform rounded-lg hover:-translate-y-1 hover:scale-100 hover:bg-gray-500 hover:shadow-lg hover:text-white ">Settings</a></li>
                {% else %}
                    <li><a href="{% url 'register:register' %}"
                        class="p-4 transition duration-300 ease-in-out delay-150 transform rounded-lg hover:-translate-y-1 hover:scale-100 hover:bg-gray-500 hover:shadow-lg hover:text-white ">Register</a></li>
                    <li><a href="{% url 'register:login' %}"
                        class="p-4 transition duration-300 ease-in-out delay-150 transform rounded-lg hover:-translate-y-1 hover:scale-100 hover:bg-gray-500 hover:shadow-lg hover:text-white ">Login</a></li>
                {% endif %}
            </ul>
        </nav>
        
        <div
        id="subjects"
        href="{% url 'a_classroom:index' %}"
        hx-get="{% url 'a_classroom:index' %}" 
        hx-target="#sidebar" 
        hx-swap="innerHTML"
        hx-trigger="load"
        style="display: none;">
        </div>

        {% if request.user.is_authenticated %}
            <aside id="sidebar" class="flex flex-col justify-between p-4 text-white bg-gray-100 border-2 shadow-xl">
            </aside>
        {% endif %}
     
        <main id="main-content" class="p-8 overflow-auto">
            {% block content %}
            {% endblock %}
        </main>
    </div>
    <!-- Above this comment -->
    <script src="{% static 'js/myjs.js' %}"></script>
</body>
</html>

a_classroom/templates/a_classroom/create_subject.html
{% extends 'a_classroom/base.html' %}
{% block title %} Create Subject {% endblock %}
{% block content %}
    <div class="flex items-center justify-center min-h-screen bg-white">
        <div class="flex items-center justify-center w-full max-w-xl p-8 bg-white border-2 border-gray-300 rounded-md shadow-xl">
            <form action="{% url 'a_classroom:create-subject' %}" method="post" class="flex flex-col items-center w-full gap-5">
                {% csrf_token %}
                
                <div class="flex flex-col items-center w-full gap-2">
                    <label for="id_course_code" class="text-lg font-semibold">COURSE CODE</label>
                    <input type="text" name="course_code" id="id_course_code" 
                           class="w-3/4 h-10 px-2 border border-gray-300 rounded-md shadow-md focus:outline-none focus:ring-2 focus:ring-black"
                           value="{{ form.course_code.value|default:'' }}" 
                           placeholder="Course Code" required>
                    {% if form.course_code.errors %}
                        <p class="text-red-500">{{ form.course_code.errors.0 }}</p>
                    {% endif %}
                </div>

                <div class="flex flex-col items-center w-full gap-2">
                    <label for="id_section_name" class="text-lg font-semibold">SECTION</label>
                    <input list="sections-list" type="text" name="section_name" id="id_section_name" 
                           class="w-3/4 h-10 px-2 border border-gray-300 rounded-md shadow-md focus:outline-none focus:ring-2 focus:ring-black"
                           value="{{ form.section_name.value|default:'' }}" 
                           placeholder="Select or Create Section" required>
                    <datalist id="sections-list">
                        {% for section in sections %}
                            <option value="{{ section.name }}"></option>
                        {% endfor %}
                    </datalist>
                    {% if form.section_name.errors %}
                        <p class="text-red-500">{{ form.section_name.errors.0 }}</p>
                    {% endif %}
                </div>

                <div class="flex flex-col items-center w-full gap-2">
                    <label for="id_name" class="text-lg font-semibold">SUBJECT</label>
                    <input type="text" name="name" id="id_name" 
                           class="w-3/4 h-10 px-2 border border-gray-300 rounded-md shadow-md focus:outline-none focus:ring-2 focus:ring-black"
                           value="{{ form.name.value|default:'' }}" 
                           placeholder="Subject" required>
                    {% if form.name.errors %}
                        <p class="text-red-500">{{ form.name.errors.0 }}</p>
                    {% endif %}
                </div>

                {% if form.non_field_errors %}
                    <div class="mt-2 text-red-500">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                <button type="submit" 
                        class="px-4 py-2 mt-4 text-white bg-black rounded-md shadow-lg cursor-pointer kw-3/4 hover:bg-gray-500">
                    Create Subject
                </button>
            </form>
        </div>
    </div>
{% endblock %}

a_classroom/templates/a_classroom/index.html
{% extends 'a_classroom/base.html' %}
{% load static tailwind_tags %}
{% block title %} index html {% endblock %}
{% tailwind_css %}
{% block content %}
<h1>Welcome Guest</h1>
{% endblock %}

a_classroom/templates/a_classroom/setting.html
{% extends 'a_classroom/base.html' %}
{% load static tailwind_tags %}
{% block title %} setting html {% endblock %}
{% tailwind_css %}
{% block content %}
<div class="flex items-center justify-center h-full w-full">
	<div id="parent-element" class="border border-solid border-gray-300 h-full w-[700px] gap-4 overflow-auto">
		<div class="flex items-center justify-center bg-gray-800 text-white">
			<h2 class="text-3xl p-4">Account Settings</h2>
		</div>
		<hr>

		<div class="flex items-center justify-center">
			<img src="{% if user_profile.image %}{{ user_profile.image.url }}{% else %}/media/mysite_images/default.jpg{% endif %}" 
            alt="Profile Image" class="rounded-circle shadow-lg h-[150px] w-[150px] object-cover border-2 border-solid border-blue-500 rounded-full m-2">
		</div>

		<div class="flex flex-col items-center justify-center h-[60px] w-full">
			<label for="id_first_name" class="text-1xl">First Name</label>
			<input class="border border-solid border-gray-300 h-full w-[50%] bg-gray-100" type="text" id="id_first_name" value="{{ user_profile.user.first_name }}" readonly>
		</div>

		<div class="flex flex-col items-center justify-center h-[60px] w-full">
			<label for="id_last_name" class="text-1x1">Last Name</label>
			<input class="border border-solid border-gray-300 h-full w-[50%] bg-gray-100" type="text" id="id_last_name" value="{{ user_profile.user.last_name }}" readonly>
		</div>

		<div class="flex flex-col items-center justify-center h-[60px] w-full">
			<label for="id_email" class="text-1x1">Email Address</label>
			<input class="border border-solid border-gray-300 h-full w-[50%] bg-gray-100" type="text" id="id_email" value="{{ email }}" readonly>
		</div>

		<div class="flex items-center justify-center h-[60px] w-full">
			<button
			class="border border-solid border-gray-300 h-[75%] w-[40%] cursor-pointer bg-blue-300 hover:bg-blue-700 hover:text-white"
			id="upload-profile"
			hx-get="{% url 'b_enrollment:upload-profile' %}"
			hx-trigger="click"
			hx-target="#parent-element"
			hx-swap="innerHTML">Upload Profile</button>
		</div>

		<div class="flex items-center justify-center h-[60px] w-full">
			<button
			class="border border-solid border-gray-300 h-[75%] w-[40%] cursor-pointer bg-blue-300 hover:bg-blue-700 hover:text-white"
			id="edit-account"
			hx-get="{% url 'a_classroom:edit-account' %}"
			hx-trigger="click"
			hx-target="#parent-element"
			hx-swap="innerHTML">Edit Account</button>
		</div>

        <form action="{% url 'logout' %}" method="post" class="flex items-center justify-center h-[60px] w-full">
            {% csrf_token %}
            <button type="submit" class="border border-solid border-gray-300 h-[75%] w-[40%] cursor-pointer bg-gray-300 hover:bg-gray-500 hover:text-white">Logout</button>
        </form>
	</div>
</div>
{% endblock %}

a_classroom/templates/a_classroom/subject_view.html
{% extends 'a_classroom/base.html' %}
{% load static tailwind_tags %}
{% block title %} index html {% endblock %}
{% tailwind_css %}
{% block content %}
    {% if subject %}
        <nav class="sticky top-0 z-50 flex justify-between col-span-2 p-6 space-x-6 text-black bg-white border-t border-b border-gray-300 border-solid shadow-xl ">
            <ul class="flex space-x-12 ">
                <li>
                    <a  class="relative pb-2 text-gray-500 transition-all duration-300 ease-in-out hover:text-blue-600 hover:after:w-full after:absolute after:-bottom-1 after:left-0 after:h-0.5 after:w-0 after:bg-blue-600 after:transition-all after:duration-300"
                        id="subject"
                        href="{% url 'a_classroom:v' subject.subject_id %}"
                        hx-get="{% url 'a_classroom:v' subject.subject_id %}" 
                        hx-target="#output" 
                        hx-swap="innerHTML"
                        hx-trigger="load delay:500ms">
                        Subject
                    </a>
                </li>
                <li>
                    <a  class="relative pb-2 text-gray-500 transition-all duration-300 ease-in-out hover:text-blue-600 hover:after:w-full after:absolute after:-bottom-1 after:left-0 after:h-0.5 after:w-0 after:bg-blue-600 after:transition-all after:duration-300"
                        id="classwork"
                        href="{% url 'a_classroom:v' subject.subject_id %}"
                        hx-get="{% url 'a_classroom:v' subject.subject_id %}"
                        hx-target="#output"
                        hx-swap="innerHTML"
                        hx-trigger="click">
                        Classwork
                    </a>
                </li>
                <li>
                    <a  class="relative pb-2 text-gray-500 transition-all duration-300 ease-in-out hover:text-blue-600 hover:after:w-full after:absolute after:-bottom-1 after:left-0 after:h-0.5 after:w-0 after:bg-blue-600 after:transition-all after:duration-300"
                        id="students"
                        href="{% url 'a_classroom:v' subject.subject_id %}"
                        hx-get="{% url 'a_classroom:v' subject.subject_id %}"
                        hx-target="#output"
                        hx-swap="innerHTML"
                        hx-trigger="click">
                        People
                    </a>
                </li>
            </ul>
        </nav>

        <div class="overflow-auto">
            <div id="output">
                <p class="text-gray-500">Loading...</p>
            </div>  
        </div>       
    {% endif %}
{% endblock %}