a_classroom/urls.py
from django.urls import path
from . import views

app_name = "a_classroom"
urlpatterns = [
    path("", views.index, name="index"),
    #
    path("subject/<str:subject_id>/", views.view_subject, name="v"),
    #
    path("create/subject/", views.CreateSubjectView.as_view(), name="create-subject"),
    #
    path("about/", views.about, name="about"),
    path("approve/<int:user_id>/", views.ApproveUserAdminView.as_view(), name="approve"),
    path("activity/<str:activity_id>/", views.ActivityView.as_view(), name="view-activity"),
    path("settings/", views.user_settings, name="setting"),
    path("edit/", views.EditAccountView.as_view(), name="edit-account"),
    path("users/", views.AdminDashboardView.as_view(), name="get-users"),
    path("pending/", views.PendingUsersView.as_view(), name="pending-users"),
    path("subjects/", views.SubjectListView.as_view(), name="get-subjects"),
    path("archived/", views.ArchivedSubjectListView.as_view(), name="archived-subjects"),
]

b_enrollment/urls.py
from django.urls import path
from . import views

app_name = "b_enrollment"
urlpatterns = [
	path("", views.JoinClassView.as_view(), name="join-a-class"),
	path("p/", views.UploadProfileView.as_view(), name="upload-profile"),]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('c/', include("a_classroom.urls")),
    path('e/', include("b_enrollment.urls")),
    path('a/', include("c_activities.urls")),
    path('p/', include("d_compiler.urls")),
    path('', include("register.urls")),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_classroom/models.py
from django.db import models
from django.contrib.auth.models import User
import random
import string

class Section(models.Model):
    name = models.CharField(max_length=100, unique=True)
    students = models.ManyToManyField(User, related_name="sections", blank=True)

class Subject(models.Model):
    instructor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subjects')
    subject_id = models.CharField(max_length=8, unique=True, editable=False)
    name = models.CharField(max_length=200)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, related_name='subjects')
    course_code = models.TextField(blank=True)
    students = models.ManyToManyField(User, related_name='joined_subjects', blank=True, through='b_enrollment.StudentSubject')
    is_archived = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.subject_id:
            self.subject_id = self.generate_unique_subject_id()
        super().save(*args, **kwargs)

    @staticmethod
    def generate_unique_subject_id():
        characters = string.ascii_uppercase + string.digits
        while True:
            unique_id = ''.join(random.choices(characters, k=8))
            if not Subject.objects.filter(subject_id=unique_id).exists():
                return unique_id

a_classroom/forms.py
from django import forms

class CreateSubjectForm(forms.Form):
    course_code = forms.CharField(label = "Course Code", max_length = 100)
    section_name = forms.CharField(label = "Section", max_length = 100)
    name = forms.CharField(label = "Subject", max_length = 200)

a_classroom/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Section, Subject
from c_activities.models import Activity, ActivitySubmission
from b_enrollment.models import UserProfile, StudentSubject
from django.urls import reverse
import json
from django.http import JsonResponse, HttpResponseRedirect, HttpRequest
from .forms import CreateSubjectForm
from django.contrib import messages
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.core.mail import send_mail
# Create your views here.
def index(request):
    if not hasattr(request.user, 'userprofile'):
        messages.error(request, "Your account is incomplete. Please contact the administrator.")
        return redirect('register:login')

    if request.user.userprofile.role == "Admin":
        if request.headers.get("HX-Request") == "true":
            return render(request, 'a_classroom/sidebar/sidebar.html')
        return render(request, 'a_classroom/a.admin/admin.html')

    elif request.user.userprofile.role == "Instructor":
        subjects = Subject.objects.filter(instructor=request.user).order_by('-subject_id')
        if request.headers.get("HX-Request") == "true":
            return render(request, 'a_classroom/sidebar/sidebar.html', {"subjects": subjects})

        return render(request, 'a_classroom/b.instructor/instructor.html', {"subjects" : subjects})

    elif request.user.userprofile.role == "Student":
        subjects = list(request.user.joined_subjects.all())
        if request.headers.get("HX-Request") == "true":
            return render(request, 'a_classroom/sidebar/sidebar.html', {"subjects" : subjects})

        return render(request, 'a_classroom/c.student/student.html', {"subjects" : subjects})

    return render(request, 'a_classroom/index.html')

@method_decorator(never_cache, name='dispatch')
class CreateSubjectView(View):
    def get(self, request):
        form = CreateSubjectForm()
        sections = Section.objects.all()
        return render(request, 'a_classroom/create_subject.html', {"form": form, "sections" : sections})
    
    def post(self, request):
        form = CreateSubjectForm(request.POST)
        if form.is_valid():
            course_code = form.cleaned_data["course_code"]
            section_name = form.cleaned_data["section_name"]
            name = form.cleaned_data["name"]

            section, created = Section.objects.get_or_create(name=section_name)

            subject = Subject.objects.filter(
                instructor=request.user, 
                course_code=course_code,
                section=section, 
                name=name).first()

            if subject:
                messages.error(request, f"{course_code} for section {section_name} already exists.")
            else:
                subject = Subject.objects.create(
                    instructor=request.user,
                    course_code=course_code,
                    section=section,
                    name=name
                )
                messages.success(request, f"{course_code} for section {section_name} has been created.")
            
            form = CreateSubjectForm() 
            
            return HttpResponseRedirect(reverse("a_classroom:v", args=[subject.subject_id]))

        return render(request, 'a_classroom/create_subject.html', {"form": form})

def user_settings(request):
    user_profile = UserProfile.objects.select_related('user').get(user = request.user)
    email = request.user.email
    return render(request, 'a_classroom/setting.html', {"user_profile" : user_profile, "email" : email})

def about(request):
    return render(request, 'a_classroom/about.html')

@never_cache
def view_subject(request, subject_id):
    subject = get_object_or_404(Subject, subject_id = subject_id)
    activities = subject.activities.all().order_by('-created_at')
    students = subject.students.all()
    instructor = subject.instructor.get_full_name()
    trigger = request.headers.get("HX-Trigger")
    if request.headers.get("HX-Request") == "true":
        if trigger == "subject":
            return render(request, 'a_classroom/subject.partials/subject.html', {
                "subject" : subject,
                "activities" : activities
            })
        elif trigger == "classwork":
            return render(request, 'a_classroom/subject.partials/classworks.html', {
                "activities" : activities
            })
        elif trigger == "students":
            return render(request, 'a_classroom/subject.partials/people.html', {
                "subject" : subject,
                "instructor" : instructor,
                "students" : students
            })
    return render(request, 'a_classroom/subject_view.html', {"subject" : subject})

class EditAccountView(View):
    def get(self, request):
        trigger = request.headers.get("HX-Trigger")
        if request.headers.get("HX-Request") == "true":
            if trigger == "edit-account":
                user = get_object_or_404(User, id = request.user.id)
                return render(request, 'a_classroom/profile/edit.account.html', {"user" : user})

    def post(self, request):
        user = get_object_or_404(User, id = request.user.id)

        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        if password:
            user.set_password(password)
            update_session_auth_hash(request, user)

        user.username = username
        user.first_name = first_name
        user.last_name = last_name
        user.save()

        messages.success(request, 'You profile has been updated successfully!')

        return redirect('a_classroom:setting')

class ActivityView(View):
    def get(self, request, activity_id):
        subject_id = request.GET.get('subject_id')
        user_profile = UserProfile.objects.select_related('user').get(user = request.user)
        subject = get_object_or_404(Subject, subject_id = subject_id)
        activity = get_object_or_404(Activity, subject = subject, activity_id = activity_id)
        if request.user.userprofile.role == "Instructor":
            submissions = ActivitySubmission.objects.filter(activity = activity).select_related('student')
            return render(request, 'c_activities/activity.partial/student.submission.html', {"submissions" : submissions, "user_profile" : user_profile, "subject_id" : subject_id})
        elif request.user.userprofile.role == "Student":
            submission = ActivitySubmission.objects.filter(activity = activity, student = request.user).first()
            submissions = [submission] if submission else []
            return render(request, 'c_activities/activity.partial/student.compiler.html', {"activity" : activity, "submissions" : submissions, "user_profile" : user_profile, "subject_id" : subject_id, "subject" : subject})
        return HttpResponse("Unhandled request case.", status=400)

class HtmxTemplateView(View):
    queryset = None
    template = None
    htmx_template = None
    htmx_trigger = None
    context_name = None

    def get(self, request: HttpRequest):
        data = self.queryset() if callable(self.queryset) else self.queryset
        trigger = request.headers.get("HX-Trigger")

        if request.headers.get("HX-Request") == "true" and trigger == self.htmx_trigger:
            return render(request, self.htmx_template, {self.context_name: data})

        return render(request, self.template, {self.context_name: data})

class AdminDashboardView(HtmxTemplateView):
    queryset = User.objects.all
    template = 'a_classroom/a.admin/admin.html'
    htmx_template = 'a_classroom/a.admin/users/users.html'
    htmx_trigger = 'all-user'
    context_name = 'all_users'

class PendingUsersView(HtmxTemplateView):
    queryset = lambda self: User.objects.filter(is_active=False)
    template = 'a_classroom/a.admin/users/pending.html'
    htmx_template = 'a_classroom/a.admin/users/pending/pending.users.html'
    htmx_trigger = 'pending'
    context_name = 'pending_users'

class SubjectListView(HtmxTemplateView):
    queryset = Subject.objects.all
    template = 'a_classroom/a.admin/users/subject.html'
    htmx_template = 'a_classroom/a.admin/users/subject/subjects.html'
    htmx_trigger = 'all-subject'
    context_name = 'subjects'

class ArchivedSubjectListView(HtmxTemplateView):
    queryset = lambda self: Subject.objects.filter(is_archived=True)
    template = 'a_classroom/a.admin/users/archived.html'
    htmx_template = 'a_classroom/a.admin/users/subject/archived.subjects.html'
    htmx_trigger = 'archived'
    context_name = 'archived_subjects'

class ApproveUserAdminView(View):
    def post(self, request, user_id):
        user = get_object_or_404(User, id=user_id)
        trigger = request.headers.get("HX-Trigger")

        if request.headers.get("HX-Request") == "true" and trigger == "approve-button":
            user.is_active = True
            user.save()

            # Send approval email
            subject = "Your Account Has Been Approved"
            message = f"""Hello {user.first_name},

            Your account has been approved by the admin.

            If you signed up with Google, your default password is 123. Please change your password after logging in.
            If you registered normally, your account is now active and ready to use.

            Best regards,  
            Admin Team
            """
            try:
                send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [user.email])
            except Exception as e:

a_classroom/templates/a_classroom/sidebar/sidebar.html
{% load static tailwind_tags %}
{% tailwind_css %}
{% if request.user.is_authenticated %}
    {% if request.user.userprofile.role == "Instructor" or request.user.userprofile.role == "Student" %}
        {% if subjects %}
            <ul class="space-y-2 overflow-auto text-center max-h-[550px] scrollbar-hide" id="subjects-ul">
                {% for subject in subjects %}
                    <a href="{% url 'a_classroom:v' subject.subject_id %}?from={{ request.path }}" class="flex flex-col justify-center p-2 text-black border-2 border-black rounded-lg hover:shadow-lg hover:bg-gray-300">
                        <li class="block w-full h-full">
                            <h1 class="text-lg font-bold">{{ subject.course_code }}</h1>
                            <p>{{ subject.section.name }}</p>
                        </li>
                    </a>
                {% endfor %}
            </ul>
        {% else %}
            <h1 class="text-black">No Subject Available</h1>
        {% endif %}

        <div class="mt-4">
            {% if request.user.is_authenticated %}
                {% if request.user.userprofile.role == "Instructor" %}
                    <a href="{% url 'a_classroom:create-subject' %}">
                        <button class="p-4 text-black border-2 border-black rounded-lg bg--500 hover:bg-gray-300 cursor-pointer">
                            Create Subject
                        </button>
                    </a>
                {% elif request.user.userprofile.role == "Student" %}
                    <button
                    id="join-class"
                    hx-get="{% url 'b_enrollment:join-a-class' %}"
                    hx-trigger="click"
                    hx-target="#main-content"
                    hx-swap="innerHTML"
                    class="p-4 text-black border-2 border-black rounded-lg bg--500 hover:bg-gray-300 cursor-pointer">
                        Join Class
                    </button>
                {% endif %}
            {% endif %}
        </div>
    {% elif request.user.userprofile.role == "Admin" %}
            <ul class="space-y-2 overflow-auto text-center h-[500px] scrollbar-hide">
                <a href="{% url 'a_classroom:get-users' %}?from={{ request.path }}" class="flex justify-center p-2 text-black border-2 border-black rounded-lg hover:shadow-lg hover:bg-gray-300">
                    <li class="block w-full h-full">
                        Users
                    </li>
                </a>
                <a href="{% url 'a_classroom:pending-users' %}?from={{ request.path }}" class="flex justify-center p-2 text-black border-2 border-black rounded-lg hover:shadow-lg hover:bg-gray-300">
                    <li class="block w-full h-full">
                        Pendings
                    </li>
                </a>
                <a href="{% url 'a_classroom:get-subjects' %}?from={{ request.path }}" class="flex justify-center p-2 text-black border-2 border-black rounded-lg hover:shadow-lg hover:bg-gray-300">
                    <li class="block w-full h-full">
                        Subjects
                    </li>
                </a>
                <a href="{% url 'a_classroom:archived-subjects' %}?from={{ request.path }}" class="flex justify-center p-2 text-black border-2 border-black rounded-lg hover:shadow-lg hover:bg-gray-300">
                    <li class="block w-full h-full">
                        Archived
                    </li>
                </a>
            </ul>
    {% endif %}
{% endif %}